import type { MealPeriod } from "./dishes";

export type RestaurantMenuDish = {
  id: string;
  period: MealPeriod;
  title: string;
  description: string;
  image: string;
  imageAlt: string;
  ingredients: [string, string, string];
  flavour: string;
  serving: string;
};

const foodRoot = "/images/food/pinterest";

// A broader preview from the QuickBite board, independent of the six hero meals.
// These are food ideas for launch, not confirmed kitchen availability or prices.
export const restaurantMenuDishes: RestaurantMenuDish[] = [
  {
    id: "berry-waffles",
    period: "Breakfast",
    title: "Waffles & berries",
    description: "Golden waffles piled with strawberries and blueberries. A bright, sweet start for a slow morning or a little breakfast treat.",
    image: `${foodRoot}/berry-waffles.webp`,
    imageAlt: "A stack of golden waffles topped with strawberries and blueberries",
    ingredients: ["Waffles", "Strawberries", "Blueberries"],
    flavour: "Sweet & fruity",
    serving: "A breakfast stack",
  },
  {
    id: "amala-ewedu",
    period: "Lunch",
    title: "Amala, ewedu & stew",
    description: "Soft amala, silky ewedu and a rich pepper stew with meat. Familiar local flavours for a proper sit-down lunch.",
    image: `${foodRoot}/amala-ewedu-stew.webp`,
    imageAlt: "Amala with ewedu, red stew and assorted meat on a white plate",
    ingredients: ["Amala", "Ewedu", "Meat stew"],
    flavour: "Rich & comforting",
    serving: "A classic local plate",
  },
  {
    id: "peppered-fish-noodles",
    period: "Dinner",
    title: "Peppered fish & noodles",
    description: "A generous tangle of noodles with pepper-coated fish and vegetables. A savoury dinner with a little extra kick.",
    image: `${foodRoot}/peppered-fish-noodles.webp`,
    imageAlt: "Peppered fish served over noodles and vegetables in a tray",
    ingredients: ["Noodles", "Fish", "Peppers"],
    flavour: "Peppery & savoury",
    serving: "A filling dinner tray",
  },
  {
    id: "puff-puff-bites",
    period: "Breakfast",
    title: "Golden puff-puff bites",
    description: "Soft centres, golden edges and just enough sweetness. A bowl of puff-puff for an easy morning bite or a moment to share.",
    image: `${foodRoot}/puff-puff-paper-bowl.webp`,
    imageAlt: "Golden puff-puff in a paper-lined bowl",
    ingredients: ["Flour", "Yeast", "Sugar"],
    flavour: "Soft & lightly sweet",
    serving: "Little bites to share",
  },
  {
    id: "rice-beans-stew",
    period: "Lunch",
    title: "Rice, beans & stew",
    description: "White rice and tender beans meet a rich tomato stew. Straightforward, satisfying comfort for the middle of your day.",
    image: `${foodRoot}/rice-beans-stew.webp`,
    imageAlt: "A bowl of white rice, beans and red stew with meat",
    ingredients: ["Rice", "Beans", "Tomato stew"],
    flavour: "Hearty & homely",
    serving: "An everyday favourite",
  },
  {
    id: "egusi-greens",
    period: "Dinner",
    title: "Egusi & leafy greens",
    description: "Melon seeds, leafy vegetables and meat come together in a rich egusi soup. A warm bowl made for taking your time.",
    image: `${foodRoot}/egusi-soup.webp`,
    imageAlt: "Egusi soup with leafy greens and assorted meat",
    ingredients: ["Egusi", "Greens", "Meat"],
    flavour: "Rich & savoury",
    serving: "A comforting soup bowl",
  },
  {
    id: "akara-breakfast",
    period: "Breakfast",
    title: "Crisp golden akara",
    description: "Freshly fried bean cakes with crisp edges and a soft centre. A familiar breakfast bite that keeps things simple.",
    image: `${foodRoot}/akara-bean-cakes.webp`,
    imageAlt: "Golden akara bean cakes on a white plate",
    ingredients: ["Beans", "Onion", "Pepper"],
    flavour: "Crisp & savoury",
    serving: "Morning bites",
  },
  {
    id: "jollof-takeaway",
    period: "Lunch",
    title: "Jollof lunch box",
    description: "Jollof rice, a golden chicken portion and fried plantain, all together in one tray. A familiar favourite for a busy lunch break.",
    image: `${foodRoot}/jollof-takeaway.webp`,
    imageAlt: "Jollof rice, chicken and fried plantain in a black takeaway tray",
    ingredients: ["Jollof rice", "Chicken", "Plantain"],
    flavour: "Smoky & satisfying",
    serving: "A lunch box favourite",
  },
  {
    id: "eba-vegetable-soup",
    period: "Dinner",
    title: "Eba & vegetable soup",
    description: "Golden eba alongside a generous helping of leafy vegetable soup. Rich, warming flavours for the end of the day.",
    image: `${foodRoot}/eba-vegetable-soup.webp`,
    imageAlt: "Golden eba served beside leafy vegetable soup on a white plate",
    ingredients: ["Eba", "Greens", "Peppers"],
    flavour: "Deep & comforting",
    serving: "An evening comfort plate",
  },
  {
    id: "ofada-egg-plantain",
    period: "Lunch",
    title: "Ofada, egg & plantain",
    description: "Local rice with a rich pepper sauce, egg and golden plantain. Plenty of familiar flavour on a leaf-lined plate.",
    image: `${foodRoot}/ofada-egg-plantain.webp`,
    imageAlt: "Rice with pepper sauce, eggs and fried plantain on a leaf-lined plate",
    ingredients: ["Ofada rice", "Egg", "Plantain"],
    flavour: "Bold & peppery",
    serving: "A local lunch favourite",
  },
  {
    id: "abacha-african-salad",
    period: "Dinner",
    title: "Abacha African salad",
    description: "Cassava strips and ugba tossed with a rich dressing, onion and fish. A colourful plate full of familiar, savoury flavour.",
    image: `${foodRoot}/abacha-african-salad.webp`,
    imageAlt: "Abacha African salad with cassava strips, ugba, onion and fish",
    ingredients: ["Cassava", "Ugba", "Fish"],
    flavour: "Savoury & colourful",
    serving: "A generous salad plate",
  },
  {
    id: "beef-rice-plantain",
    period: "Lunch",
    title: "Beef, rice & plantain",
    description: "White rice, richly sauced beef and bite-sized fried plantain, finished with an egg. A generous plate with a little of everything.",
    image: `${foodRoot}/beef-rice-plantain.webp`,
    imageAlt: "White rice with sauced beef, fried plantain and an egg on a leaf-lined plate",
    ingredients: ["Rice", "Beef", "Plantain"],
    flavour: "Rich & gently sweet",
    serving: "A generous lunch plate",
  },
  {
    id: "yam-fish-sauce",
    period: "Lunch",
    title: "Yam & fish sauce",
    description: "Tender yam with fish, onions and a pepper sauce. A simple plate with the kind of flavour that feels like home.",
    image: `${foodRoot}/yam-fish-sauce.webp`,
    imageAlt: "Boiled yam served with fish, sliced onion and pepper sauce",
    ingredients: ["Yam", "Fish", "Onion"],
    flavour: "Peppery & homely",
    serving: "A comforting yam plate",
  },
  {
    id: "fish-okra",
    period: "Dinner",
    title: "Fish & okra soup",
    description: "Fish and okra in a rich, colourful soup with leafy greens. A warming bowl for a slower evening.",
    image: `${foodRoot}/seafood-okra.webp`,
    imageAlt: "Fish and okra soup with leafy greens in a dark bowl",
    ingredients: ["Okra", "Fish", "Greens"],
    flavour: "Rich & warming",
    serving: "A hearty soup bowl",
  },
  {
    id: "assorted-meat-stew",
    period: "Dinner",
    title: "Assorted meat stew",
    description: "A bowl of assorted meat in a deep red pepper stew. Bold, familiar flavours to round out your evening meal.",
    image: `${foodRoot}/assorted-meat-stew.webp`,
    imageAlt: "Assorted meat in a rich red stew in a white bowl",
    ingredients: ["Meat", "Tomatoes", "Peppers"],
    flavour: "Bold & spicy",
    serving: "A rich stew bowl",
  },
];
