export const navThemes = {
  hero: {
    surface: "#2a211d",
    foreground: "#fffaf5",
    muted: "#ffe7d7",
    icon: "#ff6b00",
    action: "#ff6b00",
    actionText: "#ffffff",
    underline: "#ff6b00",
    chip: "#fffaf5",
    chipText: "#2a211d",
    pageBackground: "#2a211d",
    pageForeground: "#fffaf5",
    logo: "light",
  },
  light: {
    surface: "#2a211d",
    foreground: "#fffaf5",
    muted: "#ffe7d7",
    icon: "#ff6b00",
    action: "#ff6b00",
    actionText: "#ffffff",
    underline: "#ff6b00",
    chip: "#fffaf5",
    chipText: "#2a211d",
    pageBackground: "#fffaf5",
    pageForeground: "#2a211d",
    logo: "light",
  },
  dark: {
    surface: "#fffaf5",
    foreground: "#2a211d",
    muted: "#6d5c52",
    icon: "#c24f00",
    action: "#2a211d",
    actionText: "#fffaf5",
    underline: "#ff6b00",
    chip: "#ffe7d7",
    chipText: "#2a211d",
    pageBackground: "#2a211d",
    pageForeground: "#fffaf5",
    logo: "color",
  },
  accent: {
    surface: "#2a211d",
    foreground: "#fffaf5",
    muted: "#ffe7d7",
    icon: "#ff6b00",
    action: "#ff6b00",
    actionText: "#ffffff",
    underline: "#ff6b00",
    chip: "#fffaf5",
    chipText: "#2a211d",
    pageBackground: "#fff0e4",
    pageForeground: "#2a211d",
    logo: "light",
  },
  neutral: {
    surface: "#2a211d",
    foreground: "#fffaf5",
    muted: "#ffe7d7",
    icon: "#ff6b00",
    action: "#ff6b00",
    actionText: "#ffffff",
    underline: "#ff6b00",
    chip: "#fffaf5",
    chipText: "#2a211d",
    pageBackground: "#fff0e4",
    pageForeground: "#2a211d",
    logo: "light",
  },
} as const;

export type NavTheme = keyof typeof navThemes;
