export const navThemes = {
  hero: {
    surface: "#000000",
    foreground: "#ffffff",
    muted: "#ffd8bd",
    icon: "#f06400",
    action: "#f15f00",
    actionText: "#ffffff",
    underline: "#f15f00",
    chip: "#ffffff",
    chipText: "#24180f",
    pageBackground: "#160d08",
    pageForeground: "#fff8ef",
    logo: "light",
  },
  light: {
    surface: "#000000",
    foreground: "#ffffff",
    muted: "#f1c5a4",
    icon: "#f06400",
    action: "#f15f00",
    actionText: "#ffffff",
    underline: "#e25f00",
    chip: "#ffffff",
    chipText: "#24180f",
    pageBackground: "#fffdf9",
    pageForeground: "#21170f",
    logo: "light",
  },
  dark: {
    surface: "#fff7ef",
    foreground: "#24180f",
    muted: "#7d6757",
    icon: "#c24f00",
    action: "#000000",
    actionText: "#ffffff",
    underline: "#e25f00",
    chip: "#fff3e8",
    chipText: "#8a3a00",
    pageBackground: "#160d08",
    pageForeground: "#fff8ef",
    logo: "color",
  },
  accent: {
    surface: "#1c1009",
    foreground: "#fff8ef",
    muted: "#e8b98d",
    icon: "#ff8c3d",
    action: "#f15f00",
    actionText: "#ffffff",
    underline: "#ff8c3d",
    chip: "#ffffff",
    chipText: "#24180f",
    pageBackground: "#fff7ef",
    pageForeground: "#21170f",
    logo: "light",
  },
  neutral: {
    surface: "#1c1009",
    foreground: "#fff8ef",
    muted: "#e8b98d",
    icon: "#ff8c3d",
    action: "#f15f00",
    actionText: "#ffffff",
    underline: "#ff8c3d",
    chip: "#ffffff",
    chipText: "#24180f",
    pageBackground: "#fff8f1",
    pageForeground: "#24180f",
    logo: "light",
  },
} as const;

export type NavTheme = keyof typeof navThemes;
