import { Bike, BriefcaseBusiness, ClipboardCheck, Code2, HeartHandshake, Megaphone, Palette, Store } from "lucide-react";

export const companyProfiles = [
  {
    id: "product",
    label: "Product & design",
    shortLabel: "The experience",
    title: "Thoughtful by design.",
    description: "Turning everyday food runs into something that feels effortless. Simple discovery, clear choices and a little delight along the way.",
    focus: "Making room for the everyday.",
    icon: Palette,
    image: "/images/team/white-ninja.webp",
    imageAlt: "White knitted ninja art toy",
    portraitPosition: "object-[50%_50%]",
  },
  {
    id: "engineering",
    label: "Engineering",
    shortLabel: "The builders",
    title: "Small details. Big care.",
    description: "Connecting the pieces behind each food run. Building a useful, dependable product around the people who will use it.",
    focus: "Good ideas, carefully built.",
    icon: Code2,
    image: "/images/team/demo-robot.webp",
    imageAlt: "Grey hoodie robot with glowing eyes",
    portraitPosition: "object-[46%_50%]",
  },
  {
    id: "partnerships",
    label: "Kitchen partnerships",
    shortLabel: "The local connection",
    title: "Keeping it local.",
    description: "Listening to the kitchens that give a neighbourhood its flavour. Bringing their food, stories and perspective to the QuickBite table.",
    focus: "Great food starts with people.",
    icon: Store,
    image: "/images/team/black-ninja.webp",
    imageAlt: "Black art-toy ninja with a red headband",
    portraitPosition: "object-[54%_50%]",
  },
  {
    id: "community",
    label: "Community & care",
    shortLabel: "The people people",
    title: "A bigger table for all.",
    description: "Making space for food lovers, kitchens and future riders. Learning from real routines, shared stories and the community around us.",
    focus: "A little local goodness, together.",
    icon: HeartHandshake,
    image: "/images/team/orange-robot.webp",
    imageAlt: "Friendly orange robot forming a heart with its hands",
    portraitPosition: "object-[50%_50%]",
  },
  {
    id: "rider-operations",
    label: "Rider operations",
    shortLabel: "The everyday journey",
    title: "Every journey matters.",
    description: "Thinking through the journey between kitchen and doorstep. Clear handovers, useful rider tools and care for the people on the move.",
    focus: "Care that goes the distance.",
    icon: Bike,
    image: "/images/team/helmet-explorer.webp",
    imageAlt: "Art-toy explorer in a white helmet and a lime-green jacket",
    portraitPosition: "object-[50%_50%]",
  },
  {
    id: "brand-growth",
    label: "Brand & growth",
    shortLabel: "The storytellers",
    title: "Good stories travel.",
    description: "Sharing the flavours, kitchens and little moments that make QuickBite feel local. Helping more people find their place at the table.",
    focus: "More people. More local goodness.",
    icon: Megaphone,
    image: "/images/team/dinosaur-character.webp",
    imageAlt: "Smiling art-toy character wearing a green dinosaur costume",
    portraitPosition: "object-[50%_50%]",
  },
  {
    id: "quality-research",
    label: "Quality & research",
    shortLabel: "The curious minds",
    title: "Always learning, together.",
    description: "Asking questions, listening closely and testing the little details. Using everyday feedback to make each food run feel a little better.",
    focus: "Listen. Learn. Make it better.",
    icon: ClipboardCheck,
    image: "/images/team/teal-robot.webp",
    imageAlt: "Teal robot art toy displayed on a round wooden stand",
    portraitPosition: "object-[50%_50%]",
  },
  {
    id: "business-operations",
    label: "Business operations",
    shortLabel: "The steady hands",
    title: "The care behind the scenes.",
    description: "Joining up the plans, people and day-to-day details. Keeping the team organised as we build something useful for our community.",
    focus: "Keeping good things moving.",
    icon: BriefcaseBusiness,
    image: "/images/team/astronaut-toy.webp",
    imageAlt: "Dark astronaut art toy with a round helmet and oversized boots",
    portraitPosition: "object-[50%_50%]",
  },
] as const;

export const companyContent = {
  hero: {
    eyebrow: "About QuickBite",
    title: ["The people", "behind the bite."],
    sharedPurpose: "One shared appetite",
    primaryAction: { label: "Say hello", href: "/contact" },
    secondaryAction: { label: "Our plans", href: "#business-plan" },
    skillsTitle: "Different skills. One team.",
    skillsLabel: "Choose a team profile",
    keyboardInstructions: "Use the arrow keys to explore the profiles, or Home and End to jump to the first and last profile.",
    previousLabel: "Previous team profile",
    nextLabel: "Next team profile",
  },
  cta: {
    heading: "A bigger table",
    supportingCopy: "Pull up a chair. Find your next favourite.",
    actionLabel: "Explore restaurants",
    actionHref: "/restaurants",
  },
} as const;
